### ISSUE TITLE
VIRUS!

### ISSUE THREAD

**Issue by alextronfun** [kasuganosoras/ModelUnlockerGUI#2]
![image](https://github.com/kasuganosoras/ModelUnlockerGUI/assets/105593469/0430596b-5e1d-4a37-8d55-0a87038008fb)

**Comment by kasuganosoras** [comment]
![image](https://github.com/kasuganosoras/ModelUnlockerGUI/assets/34357771/69dc372f-d581-4896-885b-40be8b54a847)
